import React, { useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { COLORS, RADIUS, SPACING } from '@/constants/theme';
import { isSupabaseConfigured, supabase } from '@/lib/supabase';
import { restoreFromCloud, syncToCloud } from '@/lib/cloudSync';

export default function Account(){
 const router=useRouter();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [userEmail,setUserEmail]=useState<string|null>(null);const [loading,setLoading]=useState(false);
 useEffect(()=>{if(!supabase)return;supabase.auth.getUser().then(({data})=>setUserEmail(data.user?.email||null));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUserEmail(s?.user.email||null));return()=>data.subscription.unsubscribe()},[]);
 const run=async(fn:()=>Promise<any>,ok:string)=>{try{setLoading(true);await fn();Alert.alert('สำเร็จ',ok)}catch(e:any){Alert.alert('เกิดข้อผิดพลาด',e.message||String(e))}finally{setLoading(false)}};
 if(!isSupabaseConfigured)return <SafeAreaView style={s.safe}><View style={s.top}><Pressable onPress={()=>router.back()}><Ionicons name="chevron-back" size={26} color={COLORS.text}/></Pressable><Text style={s.title}>บัญชีและ Cloud Sync</Text></View><View style={s.empty}><Ionicons name="cloud-offline" size={34} color={COLORS.primary}/><Text style={s.emptyTitle}>ยังไม่ได้เชื่อม Supabase</Text><Text style={s.muted}>คัดลอก .env.example เป็น .env แล้วใส่ EXPO_PUBLIC_SUPABASE_URL และ EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY จากนั้นรัน supabase/schema.sql ใน SQL Editor</Text></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><View style={s.top}><Pressable onPress={()=>router.back()}><Ionicons name="chevron-back" size={26} color={COLORS.text}/></Pressable><Text style={s.title}>บัญชีและ Cloud Sync</Text></View><View style={s.content}>{userEmail?<><View style={s.profile}><View style={s.avatar}><Ionicons name="person" size={27} color={COLORS.primary}/></View><View><Text style={s.profileTitle}>เข้าสู่ระบบแล้ว</Text><Text style={s.muted}>{userEmail}</Text></View></View><Pressable style={s.primary} disabled={loading} onPress={()=>run(syncToCloud,'อัปโหลดข้อมูลขึ้น Cloud แล้ว')}><Ionicons name="cloud-upload" size={20} color="#fff"/><Text style={s.primaryText}>Sync ข้อมูลขึ้น Cloud</Text></Pressable><Pressable style={s.secondary} disabled={loading} onPress={()=>run(restoreFromCloud,'กู้ข้อมูลจาก Cloud แล้ว')}><Ionicons name="cloud-download" size={20} color={COLORS.primary}/><Text style={s.secondaryText}>Restore จาก Cloud</Text></Pressable><Pressable style={s.signout} onPress={()=>run(()=>supabase!.auth.signOut(),'ออกจากระบบแล้ว')}><Text style={s.signoutText}>ออกจากระบบ</Text></Pressable></>:<><Text style={s.label}>อีเมล</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" style={s.input}/><Text style={s.label}>รหัสผ่าน</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry style={s.input}/><Pressable style={s.primary} disabled={loading} onPress={()=>run(async()=>{const {error}=await supabase!.auth.signInWithPassword({email,password});if(error)throw error},'เข้าสู่ระบบแล้ว')}><Text style={s.primaryText}>เข้าสู่ระบบ</Text></Pressable><Pressable style={s.secondary} disabled={loading} onPress={()=>run(async()=>{const {error}=await supabase!.auth.signUp({email,password});if(error)throw error},'สร้างบัญชีแล้ว โปรดตรวจสอบอีเมลถ้าระบบกำหนดให้ยืนยัน')}><Text style={s.secondaryText}>สร้างบัญชี</Text></Pressable></>}</View></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:COLORS.background},top:{height:64,paddingHorizontal:SPACING.md,flexDirection:'row',alignItems:'center',gap:10,backgroundColor:COLORS.surface,borderBottomWidth:1,borderBottomColor:COLORS.border},title:{fontSize:20,fontWeight:'900',color:COLORS.text},content:{padding:SPACING.lg,gap:10},empty:{margin:SPACING.lg,backgroundColor:COLORS.surface,borderRadius:RADIUS.lg,padding:25,alignItems:'center',borderWidth:1,borderColor:COLORS.border},emptyTitle:{fontWeight:'900',fontSize:18,color:COLORS.text,marginTop:10},muted:{color:COLORS.textMuted,lineHeight:21,marginTop:4},label:{fontSize:12,fontWeight:'900',color:COLORS.textMuted,marginTop:6},input:{height:50,borderRadius:RADIUS.md,borderWidth:1,borderColor:COLORS.border,backgroundColor:COLORS.surface,paddingHorizontal:13,color:COLORS.text},primary:{height:50,borderRadius:RADIUS.md,backgroundColor:COLORS.dark,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8,marginTop:8},primaryText:{color:'#fff',fontWeight:'900'},secondary:{height:50,borderRadius:RADIUS.md,backgroundColor:COLORS.surface,borderWidth:1,borderColor:COLORS.border,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},secondaryText:{color:COLORS.primary,fontWeight:'900'},profile:{backgroundColor:COLORS.surface,borderRadius:RADIUS.lg,padding:16,flexDirection:'row',alignItems:'center',gap:12,borderWidth:1,borderColor:COLORS.border},avatar:{width:50,height:50,borderRadius:25,backgroundColor:'#E8F6F6',alignItems:'center',justifyContent:'center'},profileTitle:{fontWeight:'900',fontSize:17,color:COLORS.text},signout:{height:46,alignItems:'center',justifyContent:'center'},signoutText:{color:COLORS.danger,fontWeight:'800'}});
