import React, { useMemo } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { PLACES, PROVINCES } from '@/data/catalog';
import { COLORS, RADIUS, SPACING } from '@/constants/theme';
import { useTravelStore } from '@/store/useTravelStore';
import { Region } from '@/types';

const REGIONS:Region[]=['ภาคเหนือ','ภาคอีสาน','ภาคกลาง','ภาคตะวันออก','ภาคตะวันตก','ภาคใต้'];
export default function Analytics(){
 const router=useRouter();const {visitedProvinceIds,visitedPlaceIds,trips,journals,wishlistPlaceIds}=useTravelStore();
 const regionData=useMemo(()=>REGIONS.map(r=>{const total=PROVINCES.filter(p=>p.region===r).length;const visited=PROVINCES.filter(p=>p.region===r&&visitedProvinceIds.includes(p.id)).length;return {r,total,visited,pct:Math.round(visited/total*100)}}),[visitedProvinceIds]);
 const categories=useMemo(()=>{const count:Record<string,number>={};PLACES.filter(p=>visitedPlaceIds.includes(p.id)).forEach(p=>count[p.category]=(count[p.category]||0)+1);return Object.entries(count).sort((a,b)=>b[1]-a[1]);},[visitedPlaceIds]);
 const expense=journals.reduce((s,j)=>s+j.expense,0);const overall=Math.round(visitedProvinceIds.length/77*100);
 return <SafeAreaView style={s.safe}><View style={s.top}><Pressable onPress={()=>router.back()}><Ionicons name="chevron-back" size={26} color={COLORS.text}/></Pressable><View><Text style={s.title}>Travel Analytics</Text><Text style={s.sub}>สถิติการเดินทางของคุณ</Text></View></View><ScrollView contentContainerStyle={s.content}>
  <View style={s.hero}><Text style={s.heroLabel}>เที่ยวไทยแล้ว</Text><Text style={s.heroNum}>{overall}%</Text><Text style={s.heroSub}>{visitedProvinceIds.length} จาก 77 จังหวัด</Text><View style={s.heroBar}><View style={[s.heroFill,{width:`${Math.max(2,overall)}%`}]}/></View></View>
  <View style={s.metrics}><Metric icon="location" n={visitedPlaceIds.length} label="สถานที่ไปแล้ว"/><Metric icon="heart" n={wishlistPlaceIds.length} label="Wishlist"/><Metric icon="airplane" n={trips.length} label="ทริป"/><Metric icon="wallet" n={expense.toLocaleString()} label="บาทที่บันทึก"/></View>
  <Text style={s.section}>ความคืบหน้าตามภาค</Text><View style={s.card}>{regionData.map(x=><View key={x.r} style={s.region}><View style={s.row}><Text style={s.regionName}>{x.r}</Text><Text style={s.regionCount}>{x.visited}/{x.total} · {x.pct}%</Text></View><View style={s.bar}><View style={[s.fill,{width:`${Math.max(1,x.pct)}%`}]}/></View></View>)}</View>
  <Text style={s.section}>หมวดที่เที่ยวบ่อย</Text><View style={s.card}>{categories.length?categories.map(([cat,n],i)=><View key={cat} style={s.cat}><View style={[s.rank,{backgroundColor:i===0?COLORS.gold:'#E8F1F2'}]}><Text style={s.rankText}>{i+1}</Text></View><Text style={s.catName}>{cat}</Text><Text style={s.catN}>{n} ที่</Text></View>):<Text style={s.muted}>ทำเครื่องหมายสถานที่ว่า “ไปแล้ว” เพื่อเริ่มสร้างสถิติหมวดที่ชอบ</Text>}</View>
  <Text style={s.section}>Achievements</Text><View style={s.badges}><Badge icon="compass" title="นักสำรวจ" unlocked={visitedProvinceIds.length>=5}/><Badge icon="heart" title="นักวางฝัน" unlocked={wishlistPlaceIds.length>=5}/><Badge icon="book" title="นักบันทึก" unlocked={journals.length>=3}/><Badge icon="map" title="ครบทุกภาค" unlocked={REGIONS.every(r=>regionData.find(x=>x.r===r)!.visited>0)}/></View>
 </ScrollView></SafeAreaView>
}
function Metric({icon,n,label}:{icon:any;n:any;label:string}){return <View style={s.metric}><Ionicons name={icon} size={20} color={COLORS.primary}/><Text style={s.metricN}>{n}</Text><Text style={s.metricLabel}>{label}</Text></View>}
function Badge({icon,title,unlocked}:{icon:any;title:string;unlocked:boolean}){return <View style={[s.badge,!unlocked&&{opacity:.42}]}><Ionicons name={icon} size={27} color={unlocked?COLORS.rating:COLORS.textMuted}/><Text style={s.badgeTitle}>{title}</Text><Text style={s.badgeState}>{unlocked?'ปลดล็อกแล้ว':'ยังไม่ปลดล็อก'}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:COLORS.background},top:{padding:SPACING.md,backgroundColor:COLORS.surface,borderBottomWidth:1,borderBottomColor:COLORS.border,flexDirection:'row',alignItems:'center',gap:10},title:{fontSize:22,fontWeight:'900',color:COLORS.text},sub:{fontSize:12,color:COLORS.textMuted},content:{padding:SPACING.lg,paddingBottom:60,gap:14},hero:{backgroundColor:COLORS.dark,borderRadius:RADIUS.lg,padding:22},heroLabel:{color:'#A8C8C1',fontWeight:'800'},heroNum:{fontSize:48,fontWeight:'900',color:'#fff',marginTop:5},heroSub:{color:'#C7D9D5'},heroBar:{height:9,borderRadius:10,backgroundColor:'#24483F',overflow:'hidden',marginTop:16},heroFill:{height:'100%',backgroundColor:COLORS.gold},metrics:{flexDirection:'row',flexWrap:'wrap',gap:10},metric:{width:'48%',backgroundColor:COLORS.surface,borderRadius:RADIUS.md,padding:14,borderWidth:1,borderColor:COLORS.border},metricN:{fontSize:22,fontWeight:'900',color:COLORS.text,marginTop:6},metricLabel:{fontSize:11,color:COLORS.textMuted},section:{fontSize:18,fontWeight:'900',color:COLORS.text,marginTop:3},card:{backgroundColor:COLORS.surface,borderRadius:RADIUS.lg,padding:16,borderWidth:1,borderColor:COLORS.border,gap:12},region:{gap:6},row:{flexDirection:'row',justifyContent:'space-between'},regionName:{fontWeight:'800',color:COLORS.text},regionCount:{fontSize:12,color:COLORS.textMuted},bar:{height:7,borderRadius:8,backgroundColor:'#E6ECEE',overflow:'hidden'},fill:{height:'100%',backgroundColor:COLORS.primary},cat:{flexDirection:'row',alignItems:'center',gap:10},rank:{width:32,height:32,borderRadius:10,alignItems:'center',justifyContent:'center'},rankText:{fontWeight:'900',color:COLORS.text},catName:{flex:1,fontWeight:'800',color:COLORS.text},catN:{color:COLORS.textMuted},muted:{color:COLORS.textMuted,lineHeight:20},badges:{flexDirection:'row',flexWrap:'wrap',gap:10},badge:{width:'48%',backgroundColor:COLORS.surface,borderRadius:RADIUS.md,padding:16,borderWidth:1,borderColor:COLORS.border},badgeTitle:{fontWeight:'900',color:COLORS.text,marginTop:8},badgeState:{fontSize:11,color:COLORS.textMuted,marginTop:2}});
