import React, { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { PLACES } from '@/data/catalog';
import { COLORS, RADIUS, SPACING } from '@/constants/theme';
import { useTravelStore } from '@/store/useTravelStore';

const MOODS=['😍','😊','😌','🤩','🥹'];
export default function Journal(){
 const router=useRouter();const {journals,addJournal,deleteJournal,visitedPlaceIds}=useTravelStore();const [open,setOpen]=useState(false);const [title,setTitle]=useState('ความทรงจำจากทริป');const [note,setNote]=useState('');const [expense,setExpense]=useState('0');const [mood,setMood]=useState('😊');const [rating,setRating]=useState(5);const [placeId,setPlaceId]=useState(visitedPlaceIds[0]||PLACES[0].id);
 const save=()=>{addJournal({id:String(Date.now()),placeId,date:new Date().toISOString().slice(0,10),title:title.trim()||'บันทึกการเดินทาง',note,mood,rating,expense:Number(expense)||0});setNote('');setOpen(false)};
 return <SafeAreaView style={s.safe}><View style={s.top}><Pressable onPress={()=>router.back()}><Ionicons name="chevron-back" size={26} color={COLORS.text}/></Pressable><View style={{flex:1}}><Text style={s.title}>Travel Journal</Text><Text style={s.sub}>เก็บความทรงจำ ค่าใช้จ่าย และความรู้สึก</Text></View><Pressable style={s.add} onPress={()=>setOpen(v=>!v)}><Ionicons name={open?'close':'add'} size={23} color="#fff"/></Pressable></View><ScrollView contentContainerStyle={s.content}>
  {open&&<View style={s.form}><Text style={s.formTitle}>บันทึกใหม่</Text><TextInput style={s.input} value={title} onChangeText={setTitle} placeholder="หัวข้อ"/><Text style={s.label}>สถานที่</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:7}}>{PLACES.slice(0,8).map(p=><Pressable key={p.id} style={[s.chip,placeId===p.id&&s.chipOn]} onPress={()=>setPlaceId(p.id)}><Text style={[s.chipText,placeId===p.id&&s.chipTextOn]}>{p.name}</Text></Pressable>)}</ScrollView><TextInput style={[s.input,s.note]} value={note} onChangeText={setNote} placeholder="เขียนความประทับใจ..." multiline/><Text style={s.label}>ความรู้สึก</Text><View style={s.moods}>{MOODS.map(x=><Pressable key={x} onPress={()=>setMood(x)} style={[s.mood,mood===x&&s.moodOn]}><Text style={{fontSize:25}}>{x}</Text></Pressable>)}</View><Text style={s.label}>คะแนน {rating}/5</Text><View style={s.stars}>{[1,2,3,4,5].map(n=><Pressable key={n} onPress={()=>setRating(n)}><Ionicons name={n<=rating?'star':'star-outline'} size={25} color={COLORS.rating}/></Pressable>)}</View><TextInput style={s.input} value={expense} onChangeText={setExpense} keyboardType="number-pad" placeholder="ค่าใช้จ่าย (บาท)"/><Pressable style={s.save} onPress={save}><Text style={s.saveText}>บันทึก Journal</Text></Pressable></View>}
  {!journals.length?<View style={s.empty}><Ionicons name="book-outline" size={34} color={COLORS.primary}/><Text style={s.emptyTitle}>ยังไม่มีบันทึกการเดินทาง</Text><Text style={s.muted}>กด + เพื่อเริ่มเก็บเรื่องราวจากทริปของคุณ</Text></View>:journals.map(j=><View key={j.id} style={s.card}><View style={s.cardHead}><Text style={s.moodBig}>{j.mood}</Text><View style={{flex:1}}><Text style={s.cardTitle}>{j.title}</Text><Text style={s.meta}>{j.date} · {PLACES.find(p=>p.id===j.placeId)?.name||'ทริปทั่วไป'}</Text></View><Pressable onPress={()=>Alert.alert('ลบบันทึก','ยืนยันการลบ?',[{text:'ยกเลิก'},{text:'ลบ',style:'destructive',onPress:()=>deleteJournal(j.id)}])}><Ionicons name="trash-outline" size={19} color={COLORS.danger}/></Pressable></View><Text style={s.noteText}>{j.note||'ไม่มีโน้ตเพิ่มเติม'}</Text><View style={s.cardFoot}><Text style={s.rating}>{'★'.repeat(j.rating)}{'☆'.repeat(5-j.rating)}</Text><Text style={s.expense}>{j.expense.toLocaleString()} บาท</Text></View></View>)}
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:COLORS.background},top:{padding:SPACING.md,flexDirection:'row',alignItems:'center',gap:10,backgroundColor:COLORS.surface,borderBottomWidth:1,borderBottomColor:COLORS.border},title:{fontSize:22,fontWeight:'900',color:COLORS.text},sub:{fontSize:12,color:COLORS.textMuted},add:{width:42,height:42,borderRadius:21,backgroundColor:COLORS.primary,alignItems:'center',justifyContent:'center'},content:{padding:SPACING.lg,paddingBottom:70,gap:12},form:{backgroundColor:COLORS.surface,borderRadius:RADIUS.lg,padding:17,borderWidth:1,borderColor:COLORS.border,gap:10},formTitle:{fontSize:18,fontWeight:'900',color:COLORS.text},input:{minHeight:46,borderRadius:RADIUS.md,borderWidth:1,borderColor:COLORS.border,paddingHorizontal:12,color:COLORS.text,backgroundColor:'#FAFCFD'},note:{height:100,paddingTop:12,textAlignVertical:'top'},label:{fontSize:12,fontWeight:'900',color:COLORS.textMuted},chip:{paddingHorizontal:10,paddingVertical:7,borderRadius:999,borderWidth:1,borderColor:COLORS.border},chipOn:{backgroundColor:COLORS.dark,borderColor:COLORS.dark},chipText:{fontSize:12,color:COLORS.textMuted},chipTextOn:{color:'#fff',fontWeight:'800'},moods:{flexDirection:'row',gap:8},mood:{width:46,height:46,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:'#F1F5F6'},moodOn:{borderWidth:2,borderColor:COLORS.primary},stars:{flexDirection:'row',gap:5},save:{height:48,borderRadius:RADIUS.md,backgroundColor:COLORS.dark,alignItems:'center',justifyContent:'center'},saveText:{color:'#fff',fontWeight:'900'},empty:{padding:30,alignItems:'center',backgroundColor:COLORS.surface,borderRadius:RADIUS.lg,borderWidth:1,borderColor:COLORS.border},emptyTitle:{fontWeight:'900',fontSize:18,color:COLORS.text,marginTop:9},muted:{color:COLORS.textMuted,textAlign:'center',marginTop:4},card:{backgroundColor:COLORS.surface,borderRadius:RADIUS.lg,padding:16,borderWidth:1,borderColor:COLORS.border},cardHead:{flexDirection:'row',gap:10,alignItems:'center'},moodBig:{fontSize:30},cardTitle:{fontWeight:'900',fontSize:17,color:COLORS.text},meta:{fontSize:11,color:COLORS.textMuted,marginTop:2},noteText:{color:COLORS.textMuted,lineHeight:21,marginTop:12},cardFoot:{flexDirection:'row',justifyContent:'space-between',marginTop:12,paddingTop:10,borderTopWidth:1,borderTopColor:COLORS.border},rating:{color:COLORS.rating},expense:{fontWeight:'900',color:COLORS.text}});
