import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Image } from 'expo-image';
import { Ionicons } from '@expo/vector-icons';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import PlaceCard from '@/components/PlaceCard';
import { PLACES, PROVINCES } from '@/data/catalog';
import { COLORS, RADIUS, SPACING } from '@/constants/theme';
import { useTravelStore } from '@/store/useTravelStore';

export default function ProvinceDetail(){
 const {id}=useLocalSearchParams<{id:string}>();const router=useRouter();const p=PROVINCES.find(x=>x.id===id);const {visitedProvinceIds,wishlistProvinceIds,toggleVisitedProvince,toggleWishlistProvince}=useTravelStore();if(!p)return <SafeAreaView><Text>ไม่พบจังหวัด</Text></SafeAreaView>;
 const visited=visitedProvinceIds.includes(p.id),wish=wishlistProvinceIds.includes(p.id);const places=PLACES.filter(x=>x.provinceId===p.id);
 return <SafeAreaView style={s.safe} edges={['bottom']}><ScrollView contentContainerStyle={{paddingBottom:110}}>
  <View style={s.hero}><Image source={p.coverImage} style={StyleSheet.absoluteFill} contentFit="cover" cachePolicy="memory-disk"/><View style={s.shade}/><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="chevron-back" size={23} color="#fff"/></Pressable><View style={s.heroText}><Text style={s.region}>{p.region}</Text><Text style={s.title}>{p.nameTh}</Text><Text style={s.en}>{p.nameEn}</Text></View></View>
  <View style={s.content}><Text style={s.desc}>{p.description}</Text><View style={s.stats}><Stat icon="location" value={places.length||'เร็ว ๆ นี้'} label="สถานที่ในแอป"/><Stat icon="calendar" value={p.bestMonths.slice(0,3).join(' ')} label="ช่วงแนะนำ"/><Stat icon="map" value="77 จังหวัด" label="Thailand Map"/></View>
   <Text style={s.section}>ไฮไลต์ของจังหวัด</Text><View style={s.highlights}>{['ธรรมชาติ','วัฒนธรรม','อาหาร','ถ่ายรูป'].map((x,i)=><View style={s.highlight} key={x}><Ionicons name={['leaf','business','restaurant','camera'][i] as any} size={20} color={COLORS.primary}/><Text style={s.highlightText}>{x}</Text></View>)}</View>
   <Text style={s.section}>สถานที่แนะนำ</Text>{places.length?<View style={{gap:12}}>{places.map(x=><PlaceCard key={x.id} place={x} compact/>)}</View>:<View style={s.empty}><Text style={s.emptyTitle}>กำลังเพิ่มสถานที่ใน {p.nameTh}</Text><Text style={s.emptyText}>จังหวัดนี้พร้อมบันทึกสถานะได้แล้ว และจะเพิ่มข้อมูลสถานที่แบบละเอียดภายหลัง</Text></View>}
   <Pressable style={s.plan} onPress={()=>router.push('/(tabs)/trips')}><Ionicons name="calendar" size={19} color="#fff"/><Text style={s.planText}>วางแผนทริปไป {p.nameTh}</Text></Pressable>
  </View>
 </ScrollView><View style={s.bottom}><Pressable style={[s.action,visited?s.visited:s.outline]} onPress={()=>toggleVisitedProvince(p.id)}><Ionicons name="checkmark-circle" size={19} color={visited?'#fff':COLORS.text}/><Text style={[s.actionText,{color:visited?'#fff':COLORS.text}]}>{visited?'ไปแล้ว':'ไปแล้ว'}</Text></Pressable><Pressable style={[s.action,s.wish]} onPress={()=>toggleWishlistProvince(p.id)}><Ionicons name={wish?'heart':'heart-outline'} size={19} color="#fff"/><Text style={[s.actionText,{color:'#fff'}]}>{wish?'อยากไปแล้ว':'อยากไป'}</Text></Pressable></View></SafeAreaView>
}
function Stat({icon,value,label}:{icon:any;value:any;label:string}){return <View style={s.stat}><Ionicons name={icon} size={19} color={COLORS.primary}/><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:COLORS.background},hero:{height:340,position:'relative'},shade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(5,18,22,.35)',borderBottomWidth:120,borderBottomColor:'rgba(5,18,22,.48)'},back:{position:'absolute',top:50,left:18,width:44,height:44,borderRadius:22,backgroundColor:'rgba(0,0,0,.35)',alignItems:'center',justifyContent:'center'},heroText:{position:'absolute',left:22,right:22,bottom:25},region:{alignSelf:'flex-start',backgroundColor:'rgba(255,255,255,.18)',color:'#fff',fontWeight:'800',fontSize:12,paddingHorizontal:10,paddingVertical:5,borderRadius:999},title:{fontSize:34,fontWeight:'900',color:'#fff',marginTop:8},en:{color:'rgba(255,255,255,.84)',marginTop:2},content:{padding:SPACING.lg,gap:16},desc:{fontSize:16,color:COLORS.textMuted,lineHeight:26},stats:{flexDirection:'row',gap:9},stat:{flex:1,backgroundColor:COLORS.surface,borderWidth:1,borderColor:COLORS.border,borderRadius:RADIUS.md,padding:12},statValue:{fontWeight:'900',color:COLORS.text,marginTop:7,fontSize:14},statLabel:{fontSize:11,color:COLORS.textMuted,marginTop:2},section:{fontSize:19,fontWeight:'900',color:COLORS.text},highlights:{flexDirection:'row',flexWrap:'wrap',gap:9},highlight:{width:'48%',backgroundColor:COLORS.surface,borderRadius:RADIUS.md,borderWidth:1,borderColor:COLORS.border,padding:15,flexDirection:'row',alignItems:'center',gap:9},highlightText:{fontWeight:'800',color:COLORS.text},empty:{backgroundColor:COLORS.surface,borderRadius:RADIUS.md,padding:20,borderWidth:1,borderColor:COLORS.border},emptyTitle:{fontWeight:'900',color:COLORS.text},emptyText:{fontSize:13,color:COLORS.textMuted,marginTop:5,lineHeight:20},plan:{height:50,borderRadius:RADIUS.md,backgroundColor:COLORS.dark,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},planText:{color:'#fff',fontWeight:'900'},bottom:{position:'absolute',left:0,right:0,bottom:0,padding:14,paddingBottom:22,flexDirection:'row',gap:10,backgroundColor:'rgba(255,255,255,.98)',borderTopWidth:1,borderTopColor:COLORS.border},action:{flex:1,height:50,borderRadius:RADIUS.md,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},visited:{backgroundColor:COLORS.visited},outline:{backgroundColor:COLORS.surface,borderWidth:1,borderColor:COLORS.border},wish:{backgroundColor:COLORS.wishlist},actionText:{fontWeight:'900'}});
