import React, { useMemo, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { PLACES, PROVINCES } from '@/data/catalog';
import { COLORS, RADIUS, SPACING } from '@/constants/theme';
import { useTravelStore } from '@/store/useTravelStore';
import { Trip } from '@/types';

export default function Trips(){
 const {trips,createTrip,deleteTrip,wishlistPlaceIds,wishlistProvinceIds}=useTravelStore();const [open,setOpen]=useState(false);const [title,setTitle]=useState('ทริปใหม่');const [budget,setBudget]=useState('5000');const [days,setDays]=useState('3');
 const wishPlaces=useMemo(()=>PLACES.filter(p=>wishlistPlaceIds.includes(p.id)),[wishlistPlaceIds]);
 const save=()=>{const n=Math.max(1,Math.min(7,Number(days)||1));const plan:Trip={id:String(Date.now()),title:title.trim()||'ทริปใหม่',startDate:new Date().toISOString().slice(0,10),endDate:'',budget:Number(budget)||0,provinceIds:wishlistProvinceIds.slice(0,4),days:Array.from({length:n},(_,i)=>({day:i+1,placeIds:wishPlaces.filter((_,idx)=>idx%n===i).map(p=>p.id)}))};createTrip(plan);setOpen(false)};
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}>
  <View style={s.header}><View><Text style={s.title}>แผนการเดินทาง</Text><Text style={s.sub}>รวม Wishlist เป็นแผนรายวัน พร้อมงบและโน้ตทริป</Text></View><Pressable style={s.add} onPress={()=>setOpen(v=>!v)}><Ionicons name={open?'close':'add'} size={24} color="#fff"/></Pressable></View>
  {open&&<View style={s.form}><Text style={s.formTitle}>สร้างทริปใหม่</Text><TextInput style={s.input} value={title} onChangeText={setTitle} placeholder="ชื่อทริป"/><View style={s.inline}><TextInput style={[s.input,{flex:1}]} value={days} onChangeText={setDays} keyboardType="number-pad" placeholder="จำนวนวัน"/><TextInput style={[s.input,{flex:1}]} value={budget} onChangeText={setBudget} keyboardType="number-pad" placeholder="งบประมาณ"/></View><Text style={s.hint}>ระบบจะกระจาย {wishPlaces.length} สถานที่จาก Wishlist ลงในแต่ละวันให้อัตโนมัติ</Text><Pressable style={s.save} onPress={save}><Text style={s.saveText}>สร้างแผนทริป</Text></Pressable></View>}
  {!trips.length?<View style={s.empty}><Ionicons name="calendar-outline" size={34} color={COLORS.primary}/><Text style={s.emptyTitle}>ยังไม่มีแผนทริป</Text><Text style={s.emptyText}>กด + เพื่อสร้างแผน แล้วเพิ่มสถานที่จากรายการอยากไป</Text></View>:trips.map(t=><TripCard key={t.id} trip={t} onDelete={()=>Alert.alert('ลบทริป',`ลบ ${t.title}?`,[{text:'ยกเลิก'},{text:'ลบ',style:'destructive',onPress:()=>deleteTrip(t.id)}])}/>) }
 </ScrollView></SafeAreaView>
}
function TripCard({trip,onDelete}:{trip:Trip;onDelete:()=>void}){return <View style={s.card}><View style={s.cardTop}><View><Text style={s.cardTitle}>{trip.title}</Text><Text style={s.cardSub}>{trip.days.length} วัน · งบ {trip.budget.toLocaleString()} บาท</Text></View><Pressable onPress={onDelete}><Ionicons name="trash-outline" size={20} color={COLORS.danger}/></Pressable></View>{trip.provinceIds.length>0&&<View style={s.chips}>{trip.provinceIds.map(id=><Text key={id} style={s.chip}>{PROVINCES.find(p=>p.id===id)?.nameTh}</Text>)}</View>}<View style={s.timeline}>{trip.days.map(d=><View key={d.day} style={s.day}><View style={s.dayBadge}><Text style={s.dayNo}>{d.day}</Text></View><View style={{flex:1}}><Text style={s.dayTitle}>วันที่ {d.day}</Text>{d.placeIds.length?d.placeIds.map(id=><Text key={id} style={s.place}>• {PLACES.find(p=>p.id===id)?.name}</Text>):<Text style={s.placeMuted}>ยังไม่มีสถานที่ — เพิ่มได้จาก Wishlist</Text>}</View></View>)}</View></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:COLORS.background},content:{padding:SPACING.lg,paddingBottom:120,gap:14},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{fontSize:28,fontWeight:'900',color:COLORS.text},sub:{color:COLORS.textMuted,marginTop:3},add:{width:46,height:46,borderRadius:23,backgroundColor:COLORS.primary,alignItems:'center',justifyContent:'center'},form:{backgroundColor:COLORS.surface,borderRadius:RADIUS.lg,padding:18,borderWidth:1,borderColor:COLORS.border,gap:10},formTitle:{fontSize:18,fontWeight:'900',color:COLORS.text},input:{height:48,borderRadius:RADIUS.md,borderWidth:1,borderColor:COLORS.border,paddingHorizontal:13,color:COLORS.text,backgroundColor:'#FAFCFD'},inline:{flexDirection:'row',gap:10},hint:{fontSize:12,color:COLORS.textMuted,lineHeight:18},save:{height:48,borderRadius:RADIUS.md,backgroundColor:COLORS.dark,alignItems:'center',justifyContent:'center'},saveText:{color:'#fff',fontWeight:'900'},empty:{backgroundColor:COLORS.surface,borderRadius:RADIUS.lg,padding:30,alignItems:'center',borderWidth:1,borderColor:COLORS.border},emptyTitle:{fontSize:18,fontWeight:'900',color:COLORS.text,marginTop:9},emptyText:{color:COLORS.textMuted,textAlign:'center',marginTop:5},card:{backgroundColor:COLORS.surface,borderRadius:RADIUS.lg,padding:17,borderWidth:1,borderColor:COLORS.border},cardTop:{flexDirection:'row',justifyContent:'space-between'},cardTitle:{fontSize:19,fontWeight:'900',color:COLORS.text},cardSub:{color:COLORS.textMuted,fontSize:12,marginTop:3},chips:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:12},chip:{paddingHorizontal:9,paddingVertical:5,borderRadius:999,backgroundColor:'#E7F5F5',color:COLORS.primaryDark,fontWeight:'700',fontSize:12},timeline:{marginTop:14,gap:10},day:{flexDirection:'row',gap:10,paddingTop:10,borderTopWidth:1,borderTopColor:COLORS.border},dayBadge:{width:32,height:32,borderRadius:16,backgroundColor:COLORS.dark,alignItems:'center',justifyContent:'center'},dayNo:{color:'#fff',fontWeight:'900'},dayTitle:{fontWeight:'900',color:COLORS.text},place:{color:COLORS.textMuted,fontSize:13,marginTop:4},placeMuted:{color:'#9AA8B4',fontSize:12,marginTop:4,fontStyle:'italic'}});
